spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/javathon
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  mustache:
    expose-request-attributes: true

server:
  port: 8081


