spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: 1771885
  jpa:
    generate-ddl: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false


server:
  port: 8081
